# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Region.create(region_name: '北海道地方', region_name_kana: 'ホッカイドウチホウ')
Region.create(region_name: '東北地方', region_name_kana: 'トウホクチホウ')
Region.create(region_name: '北陸地方', region_name_kana: 'ホクリクチホウ')
Region.create(region_name: '関東地方', region_name_kana: 'カントウチホウ')
Region.create(region_name: '中部地方', region_name_kana: 'チュウブチホウ')
Region.create(region_name: '関西地方', region_name_kana: 'カンサイチホウ')
Region.create(region_name: '中国地方', region_name_kana: 'チュウゴクチホウ')
Region.create(region_name: '四国地方', region_name_kana: 'シコクチホウ')
Region.create(region_name: '九州地方', region_name_kana: 'キュウシュウチホウ')
Region.create(region_name: '沖縄地方', region_name_kana: 'オキナワチホウ')

Prefecture.create(prefecture_name: '北海道', prefecture_name_kana: 'ホッカイドウ', region_id: '1')
Prefecture.create(prefecture_name: '青森県', prefecture_name_kana: 'アオモリケン', region_id: '2')
Prefecture.create(prefecture_name: '秋田県', prefecture_name_kana: 'アキタケン', region_id: '2')
Prefecture.create(prefecture_name: '岩手県', prefecture_name_kana: 'イワテケン', region_id: '2')
Prefecture.create(prefecture_name: '山形県', prefecture_name_kana: 'ヤマガタケン', region_id: '2')
Prefecture.create(prefecture_name: '宮城県', prefecture_name_kana: 'ミヤギケン', region_id: '2')
Prefecture.create(prefecture_name: '福島県', prefecture_name_kana: 'フクシマケン', region_id: '2')

Municipality.create(municipality_name: '札幌市', municipality_name_kana: 'サッポロシ', prefecture_id: '1')

Municipality.create(municipality_name: '青森市', municipality_name_kana: 'アオモリシ', prefecture_id: '2')
Municipality.create(municipality_name: '弘前市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '八戸市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '黒岩市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '五所川原市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '十和田市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '三沢市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: 'むつ市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: 'つがる市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '平川市', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '平内町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '今別町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '蓬田村', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '外ヶ浜町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '鰺ヶ沢町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '深浦町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '西目屋村', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '藤崎町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '大鰐町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '田舎館村', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '板柳町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '鶴田町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '中泊町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '野辺地町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '七戸町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '六戸町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '横浜町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '東北町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '六ヶ所村', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: 'おいらせ町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '大間町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '東通村', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '風間浦村', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '佐井村', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '三戸町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '五戸町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '田子町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '南部町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '階上町', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')
Municipality.create(municipality_name: '新郷村', municipality_name_kana: 'ヒロサキシ', prefecture_id: '2')

Tag.create(tag_name: '自然', tag_name: '自然')
Tag.create(tag_name: 'レジャー', tag_name: 'レジャー')
Tag.create(tag_name: 'ツーリング', tag_name: 'ツーリング')